Repository octokit/create-octokit-project.js, pull requests merged in 2022-07, with the labels that each got.

#163 fix: specify `engines` field
  package.json
Labels: maintenance

#166 feat(create-test-action): scaffold test action to run lint only once
  lib/create-test-action.js
Labels: feature

#171 fix: replace `pika` with `pika-pack`
  lib/create-package-json.js
Labels: bug
