Repository octokit/create-octokit-project.js, pull requests merged in 2022-09, with the labels that each got.

#189 feat(test-action): add fix to create-test-action 'test' job
  lib/create-test-action.js
Labels: maintenance

#191 fix: correct help link
  lib/create-issue-templates.js
Labels: bug

#193 feat(renovate): add Renovate configuration if owner is 'octokit'
  index.js
  lib/create-renovate-config.js
Labels: feature
